### ISSUE TITLE
SEGFAULT while trying to map a CV port to a plugin

### ISSUE THREAD

**Issue by raidolo** [mod-audio/mod-host#88]
Hi @falkTX,

I'm using mod-host and mod-ui outside mod-desktop, latest commits from yesterday. I'm running latest jack2 develop branch.
I got a crash in mod-host while on mod-ui I save a CV control in a plugin. For instance I want to connect a  Control to CV port to the input level on NAM plugin, or to a drive level on the GX TubeScreamer (it doesn't matter much which plugin I use).

Basically when mod-ui issue the command "cv_map 2 input_level effect_1:Cvoutput -20.000000 20.000000 +"  mod-host crashes with segfault. 

```
PROTOCOL: received 'cv_map' '2' 'input_level' 'effect_1:Cvoutput' '-20.000000' '20.000000' '+'
Jack: JackClient::ClientNotify ref = 6 name = mod-host notify = 9
Jack: JackClient::kPortRegistrationOn port_index = 30
Jack: JackClient::PortRegister ref = 11 name = effect_2:input_level type = 32 bit float mono audio port_index = 30
Segmentation fault
```

I tried to enable the debug also, but I don't see anything more.

The strace of the process just show this:

```
write(1, "Jack: jack_set_thread_init_callb"..., 73) = 73
futex(0x58ee4257ef48, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x58ee4257eef0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x58ee4257eef0, FUTEX_WAKE_PRIVATE, 1) = 0
write(1, "Jack: JackClient::Activate\n", 27) = 27
write(1, "Jack: JackPosixThread::StartImp "..., 55) = 55
rt_sigprocmask(SIG_BLOCK, ~[], [PIPE], 8) = 0
clone3({flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, child_tid=0x7a4b64dcc990, parent_tid=0x7a4b64dcc990, exit_signal=0, stack=0x7a4b64d4c000, stack_size=0x7ff80, tls=0x7a4b64dcc6c0} => {parent_tid=[12602]}, 88) = 12602
sched_setscheduler(12602, SCHED_OTHER, [0]) = 0
rt_sigprocmask(SIG_SETMASK, [PIPE], NULL, 8) = 0
futex(0x7a4b64dcccd8, FUTEX_WAKE_PRIVATE, 1) = 1
write(30, "\6\0\0\0", 4)                = 4
write(30, "\10\0\0\0", 4)               = 4
write(30, "\v\0\0\0", 4)                = 4
write(30, "\1\0\0\0", 4)                = 4
read(30, "\0\0\0\0", 4)                 = 4
sendto(22, "resp 2\0", 7, 0, NULL, 0)   = 7
write(1, "PROTOCOL: response 'resp 2'\n", 28) = 28
recvfrom(22, "cv_map 2 input_level effect_1:Cv"..., 1024, 0, NULL, NULL) = 62
write(1, "PROTOCOL: received 'cv_map' '2' "..., 95) = 95
write(30, "\1\0\0\0", 4)                = 4
write(30, ".\1\0\0", 4)                 = 4
write(30, "\v\0\0\0", 4)                = 4
write(30, "effect_2:input_level\0\0\0\0\0\0\0\0\0\0\0\0"..., 257) = 257
write(30, "32 bit float mono audio\0\0\0\0\0\0\0\0\0"..., 33) = 33
write(30, "\1\1\0\0", 4)                = 4
write(30, "\0\0\0\0", 4)                = 4
read(30, "\0\0\0\0", 4)                 = 4
read(30, "\36\0\0\0", 4)                = 4
write(1, "Jack: JackClient::PortRegister r"..., 115) = 115
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=NULL} ---
+++ killed by SIGSEGV +++
```
Is there anything I can check?

Inside mod-desktop it works fine, I don't understand why and what could be the issue running mod-host and mod-ui outside it. I also tried using the jack instance from my debian which was 1.9.21, and it worked even with that. But outside mod-desktop it just segfault.

Thanks a lot in advance.

Regards.

**Comment by falkTX** [comment]
Try the debug build from within gdb, so we can get a stacktrace, thanks!
Something like...

```
gdb --args /path/to/mod-host -p 5555 ... -n

# run the program
r

# trigger crash

# get backtrace
bt
```

**Comment by raidolo** [comment]
Hi @falkTX 

I got this:

```
Jack: JackClient::PortRegister ref = 11 name = effect_2::bypass type = 32 bit float mono audio port_index = 30

Thread 1 "mod-host" received signal SIGSEGV, Segmentation fault.
0x00007ffff7f81d45 in ?? () from /lib/x86_64-linux-gnu/libjack.so.0
(gdb) 
(gdb) bt
#0  0x00007ffff7f81d45 in ?? () from /lib/x86_64-linux-gnu/libjack.so.0
#1  0x000055555556a122 in ?? ()
#2  0x000055555556cbdc in ?? ()
#3  0x000055555556dcda in ?? ()
#4  0x000055555556e667 in ?? ()
#5  0x000055555555a0f1 in ?? ()
#6  0x00007ffff764624a in __libc_start_call_main (main=main@entry=0x555555559ee0, argc=argc@entry=6, argv=argv@entry=0x7fffffffeb38) at ../sysdeps/nptl/libc_start_call_main.h:58
#7  0x00007ffff7646305 in __libc_start_main_impl (main=0x555555559ee0, argc=6, argv=0x7fffffffeb38, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffeb28) at ../csu/libc-start.c:360
#8  0x000055555555a331 in ?? ()
(gdb) 

```

**Comment by falkTX** [comment]
that is not really a debug build.

do a make clean and build with "make DEBUG=1"

**Comment by raidolo** [comment]
@falkTX I think I found the issue. I've compiled mod-host with the libraries from jack2 source (installed in /usr/local/lib) and it seems that the issue is gone. Let me do some more tests, but I believe that the libraries from debian 12 should not be used at this point to build mod-host.

**Comment by raidolo** [comment]
Fixed using latest jack2 "develop" branch built and installed locally in order to use the latest libraries to link mod-host binary. Just for reference: the jack2 latest commit at the time of the fix is this: https://github.com/jackaudio/jack2/commit/43e1173e3060b2ebc9b6c54058464d5145afbf6e
